{
 "title": "ChangeWatch exporter - Overview - v0.1.3",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total number of monitors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(changewatch_monitor_item)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of monitors up to date",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(changewatch_monitor_item{delta=\"none\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spread of delta's monitor",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(changewatch_monitor_item) by (delta)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "List of monitors",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "changewatch_monitor_item", "legendFormat": "{{delta}}" }
   ]
  }
 ]
}